### ISSUE TITLE
版本3.1.18 提示 Openssl is deprecated

### ISSUE THREAD

**Issue by chinphy** [easy-swoole/component#14]
版本3.1.18 提示
**EasySwoole\Component\Openssl is deprecated ,use EasySwoole\Component\Crypto instead**
实际上**Crypto** 这里面是空类， 还没达到可用状态。
（由于在开发环境里安装的早期的3.1.18版本， 当部署到服务器时拉取3.1.18版本貌似内容有变，
版本定在了3.1.18，所以暂不升级ES。）

**Comment by kiss291323003** [comment]
这边正在规划中，因此openssl标记为废弃状态，下个版本正式废弃。这几天就好了
